#!/usr/bin/env sh

set -e

# Config file generated by Home Assistant.
JSON_FILE="/data/options.json"

# Read options JSON and export values with shell-safe quoting. This preserves
# spaces, dollar signs and other special characters in passwords/host values.
if [ -f "$JSON_FILE" ]; then
    eval "$(jq -r 'to_entries[] | "export \(.key)=\(.value|tostring|@sh)"' "$JSON_FILE")"
fi

# Keep GroBro's relative config_*.json files persistent across add-on rebuilds.
# The application code remains under /app and is added explicitly to PYTHONPATH.
RUNTIME_DIR="/data/GroBro"
mkdir -p "$RUNTIME_DIR"
export PYTHONPATH="/app${PYTHONPATH:+:$PYTHONPATH}"
cd "$RUNTIME_DIR"

exec python -m grobro.ha_bridge
