"""User-facing localization helpers for Better GroBro Home Assistant discovery."""

from __future__ import annotations

import re
import time

from grobro.ha.supervisor_config import get_home_assistant_language

SUPPORTED_LANGUAGES = ("de", "en", "fr", "es", "nl")

# High-value exact names generated by Better GroBro or seen frequently in HA.
_EXACT = {
    "de": {
        "Restart Datalogger": "Datenlogger neu starten",
        "Sync Time": "Zeit synchronisieren",
        "Read All Values": "Alle Werte lesen",
        "Firmware Version": "Firmware-Version",
        "Device SN": "Geräte-Seriennummer",
        "Device Type": "Gerätetyp",
        "Online": "Online",
        "Grid frequency": "Netzfrequenz",
        "Output power": "Ausgangsleistung",
        "Output Power Limit": "Ausgangsleistungsgrenze",
        "Inverter Power": "Wechselrichterleistung",
        "Inverter temperature": "Wechselrichtertemperatur",
        "Boost temperature": "Boost-Temperatur",
        "PV total power": "PV-Gesamtleistung",
        "Battery SOC": "Batterie-SOC",
        "Battery power": "Batterieleistung",
        "Battery voltage": "Batteriespannung",
        "Battery current": "Batteriestrom",
        "Battery Charging Status": "Batterie-Ladestatus",
        "Battery Cycle Count": "Batterie-Zyklen",
        "Battery Health": "Batteriegesundheit",
        "Grid import power": "Netzbezugsleistung",
        "Grid export power": "Netzeinspeiseleistung",
        "Load power": "Lastleistung",
        "Wi-Fi Signal Strength": "WLAN-Signalstärke",
        "Update Interval": "Aktualisierungsintervall",
        "System Time": "Systemzeit",
        "Time Zone": "Zeitzone",
        "MQTT Broker": "MQTT-Broker",
        "MQTT Port": "MQTT-Port",
        "MQTT IP": "MQTT-IP",
        "DNS Server": "DNS-Server",
        "Charge Limit": "Ladegrenze",
        "Discharge Limit": "Entladegrenze",
        "Default Out Power": "Standard-Ausgangsleistung",
        "Work Mode": "Betriebsmodus",
        "Priority Mode": "Prioritätsmodus",
    },
    "fr": {
        "Restart Datalogger": "Redémarrer l'enregistreur",
        "Sync Time": "Synchroniser l'heure",
        "Read All Values": "Lire toutes les valeurs",
        "Firmware Version": "Version du firmware",
        "Device SN": "Numéro de série de l'appareil",
        "Device Type": "Type d'appareil",
        "Online": "En ligne",
        "Grid frequency": "Fréquence du réseau",
        "Output power": "Puissance de sortie",
        "Output Power Limit": "Limite de puissance de sortie",
        "Inverter Power": "Puissance de l'onduleur",
        "Inverter temperature": "Température de l'onduleur",
        "Boost temperature": "Température boost",
        "PV total power": "Puissance PV totale",
        "Battery SOC": "SOC batterie",
        "Battery power": "Puissance batterie",
        "Battery voltage": "Tension batterie",
        "Battery current": "Courant batterie",
        "Battery Charging Status": "État de charge de la batterie",
        "Battery Cycle Count": "Nombre de cycles batterie",
        "Battery Health": "Santé de la batterie",
        "Grid import power": "Puissance importée du réseau",
        "Grid export power": "Puissance injectée au réseau",
        "Load power": "Puissance de charge",
        "Wi-Fi Signal Strength": "Force du signal Wi-Fi",
        "Update Interval": "Intervalle de mise à jour",
        "System Time": "Heure système",
        "Time Zone": "Fuseau horaire",
        "MQTT Broker": "Courtier MQTT",
        "MQTT Port": "Port MQTT",
        "MQTT IP": "IP MQTT",
        "DNS Server": "Serveur DNS",
        "Charge Limit": "Limite de charge",
        "Discharge Limit": "Limite de décharge",
        "Default Out Power": "Puissance de sortie par défaut",
        "Work Mode": "Mode de fonctionnement",
        "Priority Mode": "Mode de priorité",
    },
    "es": {
        "Restart Datalogger": "Reiniciar registrador",
        "Sync Time": "Sincronizar hora",
        "Read All Values": "Leer todos los valores",
        "Firmware Version": "Versión de firmware",
        "Device SN": "Número de serie del dispositivo",
        "Device Type": "Tipo de dispositivo",
        "Online": "En línea",
        "Grid frequency": "Frecuencia de red",
        "Output power": "Potencia de salida",
        "Output Power Limit": "Límite de potencia de salida",
        "Inverter Power": "Potencia del inversor",
        "Inverter temperature": "Temperatura del inversor",
        "Boost temperature": "Temperatura boost",
        "PV total power": "Potencia FV total",
        "Battery SOC": "SOC de batería",
        "Battery power": "Potencia de batería",
        "Battery voltage": "Tensión de batería",
        "Battery current": "Corriente de batería",
        "Battery Charging Status": "Estado de carga de batería",
        "Battery Cycle Count": "Ciclos de batería",
        "Battery Health": "Salud de la batería",
        "Grid import power": "Potencia importada de red",
        "Grid export power": "Potencia exportada a red",
        "Load power": "Potencia de carga",
        "Wi-Fi Signal Strength": "Intensidad de señal Wi-Fi",
        "Update Interval": "Intervalo de actualización",
        "System Time": "Hora del sistema",
        "Time Zone": "Zona horaria",
        "MQTT Broker": "Broker MQTT",
        "MQTT Port": "Puerto MQTT",
        "MQTT IP": "IP MQTT",
        "DNS Server": "Servidor DNS",
        "Charge Limit": "Límite de carga",
        "Discharge Limit": "Límite de descarga",
        "Default Out Power": "Potencia de salida predeterminada",
        "Work Mode": "Modo de trabajo",
        "Priority Mode": "Modo de prioridad",
    },
    "nl": {
        "Restart Datalogger": "Datalogger herstarten",
        "Sync Time": "Tijd synchroniseren",
        "Read All Values": "Alle waarden lezen",
        "Firmware Version": "Firmwareversie",
        "Device SN": "Serienummer apparaat",
        "Device Type": "Apparaattype",
        "Online": "Online",
        "Grid frequency": "Netfrequentie",
        "Output power": "Uitgangsvermogen",
        "Output Power Limit": "Limiet uitgangsvermogen",
        "Inverter Power": "Omvormervermogen",
        "Inverter temperature": "Omvormertemperatuur",
        "Boost temperature": "Boosttemperatuur",
        "PV total power": "Totaal PV-vermogen",
        "Battery SOC": "Batterij-SOC",
        "Battery power": "Batterijvermogen",
        "Battery voltage": "Batterijspanning",
        "Battery current": "Batterijstroom",
        "Battery Charging Status": "Laadstatus batterij",
        "Battery Cycle Count": "Aantal batterijcycli",
        "Battery Health": "Batterijgezondheid",
        "Grid import power": "Netafnamevermogen",
        "Grid export power": "Terugleververmogen",
        "Load power": "Belastingsvermogen",
        "Wi-Fi Signal Strength": "Wi-Fi-signaalsterkte",
        "Update Interval": "Update-interval",
        "System Time": "Systeemtijd",
        "Time Zone": "Tijdzone",
        "MQTT Broker": "MQTT-broker",
        "MQTT Port": "MQTT-poort",
        "MQTT IP": "MQTT-IP",
        "DNS Server": "DNS-server",
        "Charge Limit": "Laadlimiet",
        "Discharge Limit": "Ontlaadlimiet",
        "Default Out Power": "Standaard uitgangsvermogen",
        "Work Mode": "Werkmodus",
        "Priority Mode": "Prioriteitsmodus",
    },
}

_PHRASES = {
    "de": {
        "battery discharge": "Batterieentladung",
        "battery charge": "Batterieladung",
        "grid import": "Netzbezug",
        "grid export": "Netzeinspeisung",
        "input voltage": "Eingangsspannung",
        "output voltage": "Ausgangsspannung",
        "input current": "Eingangsstrom",
        "output current": "Ausgangsstrom",
        "input power": "Eingangsleistung",
        "output power": "Ausgangsleistung",
        "apparent power": "Scheinleistung",
        "active power": "Wirkleistung",
        "energy today": "Energie heute",
        "energy total": "Gesamtenergie",
        "state of health": "Gesundheitszustand",
        "state of charge": "Ladezustand",
        "serial part": "Seriennummer Teil",
        "start time": "Startzeit",
        "end time": "Endzeit",
        "fault code": "Fehlercode",
        "warning code": "Warncode",
        "system status": "Systemstatus",
    },
    "fr": {
        "battery discharge": "décharge batterie",
        "battery charge": "charge batterie",
        "grid import": "import réseau",
        "grid export": "injection réseau",
        "input voltage": "tension d'entrée",
        "output voltage": "tension de sortie",
        "input current": "courant d'entrée",
        "output current": "courant de sortie",
        "input power": "puissance d'entrée",
        "output power": "puissance de sortie",
        "apparent power": "puissance apparente",
        "active power": "puissance active",
        "energy today": "énergie aujourd'hui",
        "energy total": "énergie totale",
        "state of health": "état de santé",
        "state of charge": "état de charge",
        "serial part": "partie du numéro de série",
        "start time": "heure de début",
        "end time": "heure de fin",
        "fault code": "code de défaut",
        "warning code": "code d'avertissement",
        "system status": "état système",
    },
    "es": {
        "battery discharge": "descarga de batería",
        "battery charge": "carga de batería",
        "grid import": "importación de red",
        "grid export": "exportación a red",
        "input voltage": "tensión de entrada",
        "output voltage": "tensión de salida",
        "input current": "corriente de entrada",
        "output current": "corriente de salida",
        "input power": "potencia de entrada",
        "output power": "potencia de salida",
        "apparent power": "potencia aparente",
        "active power": "potencia activa",
        "energy today": "energía de hoy",
        "energy total": "energía total",
        "state of health": "estado de salud",
        "state of charge": "estado de carga",
        "serial part": "parte del número de serie",
        "start time": "hora de inicio",
        "end time": "hora de fin",
        "fault code": "código de fallo",
        "warning code": "código de aviso",
        "system status": "estado del sistema",
    },
    "nl": {
        "battery discharge": "batterijontlading",
        "battery charge": "batterijlading",
        "grid import": "netafname",
        "grid export": "teruglevering",
        "input voltage": "ingangsspanning",
        "output voltage": "uitgangsspanning",
        "input current": "ingangsstroom",
        "output current": "uitgangsstroom",
        "input power": "ingangsvermogen",
        "output power": "uitgangsvermogen",
        "apparent power": "schijnbaar vermogen",
        "active power": "actief vermogen",
        "energy today": "energie vandaag",
        "energy total": "totale energie",
        "state of health": "gezondheidstoestand",
        "state of charge": "laadtoestand",
        "serial part": "serienummer deel",
        "start time": "starttijd",
        "end time": "eindtijd",
        "fault code": "foutcode",
        "warning code": "waarschuwingscode",
        "system status": "systeemstatus",
    },
}

_WORDS = {
    "de": {
        "battery": "Batterie", "temperature": "Temperatur", "temp": "Temperatur",
        "power": "Leistung", "voltage": "Spannung", "current": "Strom",
        "energy": "Energie", "today": "heute", "total": "gesamt",
        "input": "Eingang", "output": "Ausgang", "grid": "Netz",
        "charge": "Laden", "charging": "Laden", "discharge": "Entladen",
        "charged": "geladen", "discharged": "entladen", "load": "Last",
        "frequency": "Frequenz", "status": "Status", "state": "Zustand",
        "system": "System", "work": "Betrieb", "mode": "Modus",
        "enabled": "aktiviert", "start": "Start", "end": "Ende", "time": "Zeit",
        "limit": "Grenze", "default": "Standard", "smart": "Smart",
        "priority": "Priorität", "fault": "Fehler", "warning": "Warnung",
        "code": "Code", "cycle": "Zyklus", "count": "Anzahl", "health": "Gesundheit",
        "signal": "Signal", "strength": "Stärke", "serial": "Seriennummer",
        "part": "Teil", "device": "Gerät", "type": "Typ", "firmware": "Firmware",
        "version": "Version", "reserved": "Reserviert", "household": "Haushalt",
        "consumption": "Verbrauch", "allowed": "Erlaubt", "operating": "Betrieb",
        "capacity": "Kapazität", "communication": "Kommunikation", "from": "von",
        "inside": "intern", "phase": "Phase", "forward": "Vorwärts",
        "reverse": "Rückwärts", "generate": "Erzeugung", "storage": "Speicher",
        "storge": "Speicher", "maximum": "Maximum", "max": "Max.", "minimum": "Minimum",
        "min": "Min.", "cell": "Zelle", "heater": "Heizung", "fan": "Lüfter",
        "speed": "Drehzahl", "information": "Information", "software": "Software",
        "using": "Verwendet", "drycontact": "Trockenkontakt", "connect": "Verbindung",
    },
    "fr": {
        "battery": "batterie", "temperature": "température", "temp": "température",
        "power": "puissance", "voltage": "tension", "current": "courant",
        "energy": "énergie", "today": "aujourd'hui", "total": "total",
        "input": "entrée", "output": "sortie", "grid": "réseau",
        "charge": "charge", "charging": "charge", "discharge": "décharge",
        "charged": "chargée", "discharged": "déchargée", "load": "charge",
        "frequency": "fréquence", "status": "état", "state": "état",
        "system": "système", "work": "fonctionnement", "mode": "mode",
        "enabled": "activé", "start": "début", "end": "fin", "time": "heure",
        "limit": "limite", "default": "défaut", "smart": "intelligent",
        "priority": "priorité", "fault": "défaut", "warning": "avertissement",
        "code": "code", "cycle": "cycle", "count": "nombre", "health": "santé",
        "signal": "signal", "strength": "force", "serial": "série", "part": "partie",
        "device": "appareil", "type": "type", "firmware": "firmware",
        "version": "version", "reserved": "réservé", "household": "foyer",
        "consumption": "consommation", "allowed": "autorisé", "operating": "fonctionnement",
        "capacity": "capacité", "communication": "communication", "from": "de",
        "inside": "interne", "phase": "phase", "forward": "direct",
        "reverse": "inverse", "generate": "production", "storage": "stockage",
        "storge": "stockage", "maximum": "maximum", "max": "max.", "minimum": "minimum",
        "min": "min.", "cell": "cellule", "heater": "chauffage", "fan": "ventilateur",
        "speed": "vitesse", "information": "information", "software": "logiciel",
        "using": "utilisée", "connect": "connexion",
    },
    "es": {
        "battery": "batería", "temperature": "temperatura", "temp": "temperatura",
        "power": "potencia", "voltage": "tensión", "current": "corriente",
        "energy": "energía", "today": "hoy", "total": "total",
        "input": "entrada", "output": "salida", "grid": "red",
        "charge": "carga", "charging": "carga", "discharge": "descarga",
        "charged": "cargada", "discharged": "descargada", "load": "carga",
        "frequency": "frecuencia", "status": "estado", "state": "estado",
        "system": "sistema", "work": "trabajo", "mode": "modo",
        "enabled": "activado", "start": "inicio", "end": "fin", "time": "hora",
        "limit": "límite", "default": "predeterminado", "smart": "inteligente",
        "priority": "prioridad", "fault": "fallo", "warning": "aviso",
        "code": "código", "cycle": "ciclo", "count": "número", "health": "salud",
        "signal": "señal", "strength": "intensidad", "serial": "serie", "part": "parte",
        "device": "dispositivo", "type": "tipo", "firmware": "firmware",
        "version": "versión", "reserved": "reservado", "household": "hogar",
        "consumption": "consumo", "allowed": "permitido", "operating": "funcionamiento",
        "capacity": "capacidad", "communication": "comunicación", "from": "de",
        "inside": "interna", "phase": "fase", "forward": "directa",
        "reverse": "inversa", "generate": "generación", "storage": "almacenamiento",
        "storge": "almacenamiento", "maximum": "máximo", "max": "máx.", "minimum": "mínimo",
        "min": "mín.", "cell": "celda", "heater": "calentador", "fan": "ventilador",
        "speed": "velocidad", "information": "información", "software": "software",
        "using": "utilizada", "connect": "conexión",
    },
    "nl": {
        "battery": "batterij", "temperature": "temperatuur", "temp": "temperatuur",
        "power": "vermogen", "voltage": "spanning", "current": "stroom",
        "energy": "energie", "today": "vandaag", "total": "totaal",
        "input": "ingang", "output": "uitgang", "grid": "net",
        "charge": "laden", "charging": "laden", "discharge": "ontladen",
        "charged": "geladen", "discharged": "ontladen", "load": "belasting",
        "frequency": "frequentie", "status": "status", "state": "toestand",
        "system": "systeem", "work": "werking", "mode": "modus",
        "enabled": "ingeschakeld", "start": "start", "end": "einde", "time": "tijd",
        "limit": "limiet", "default": "standaard", "smart": "slim",
        "priority": "prioriteit", "fault": "fout", "warning": "waarschuwing",
        "code": "code", "cycle": "cyclus", "count": "aantal", "health": "gezondheid",
        "signal": "signaal", "strength": "sterkte", "serial": "serienummer", "part": "deel",
        "device": "apparaat", "type": "type", "firmware": "firmware",
        "version": "versie", "reserved": "gereserveerd", "household": "huishouden",
        "consumption": "verbruik", "allowed": "toegestaan", "operating": "bedrijf",
        "capacity": "capaciteit", "communication": "communicatie", "from": "van",
        "inside": "intern", "phase": "fase", "forward": "voorwaarts",
        "reverse": "achterwaarts", "generate": "opwekking", "storage": "opslag",
        "storge": "opslag", "maximum": "maximum", "max": "max.", "minimum": "minimum",
        "min": "min.", "cell": "cel", "heater": "verwarming", "fan": "ventilator",
        "speed": "snelheid", "information": "informatie", "software": "software",
        "using": "gebruikt", "connect": "verbinding",
    },
}


def normalize_language(language: str | None) -> str:
    base = str(language or "en").strip().lower().replace("_", "-").split("-")[0]
    return base if base in SUPPORTED_LANGUAGES else "en"


_LANGUAGE_CACHE = {"value": "en", "checked_at": 0.0}


def runtime_language() -> str:
    """Use Home Assistant's backend language for discovery names.

    Refresh periodically so a temporary Supervisor/Core API failure at startup
    cannot lock the add-on to the English fallback for its entire lifetime.
    """
    now = time.monotonic()
    if now - float(_LANGUAGE_CACHE["checked_at"]) < 60:
        return str(_LANGUAGE_CACHE["value"])

    language = normalize_language(get_home_assistant_language("en"))
    _LANGUAGE_CACHE["value"] = language
    _LANGUAGE_CACHE["checked_at"] = now
    return language


def reset_language_cache() -> None:
    """Reset the runtime language cache for tests or explicit rediscovery."""
    _LANGUAGE_CACHE["value"] = "en"
    _LANGUAGE_CACHE["checked_at"] = 0.0


def _replace_phrases(text: str, language: str) -> str:
    for source, target in sorted(
        _PHRASES.get(language, {}).items(),
        key=lambda item: len(item[0]),
        reverse=True,
    ):
        text = re.sub(re.escape(source), target, text, flags=re.IGNORECASE)
    return text


def _replace_words(text: str, language: str) -> str:
    words = _WORDS.get(language, {})

    def repl(match: re.Match[str]) -> str:
        word = match.group(0)
        translated = words.get(word.lower())
        return translated if translated is not None else word

    return re.sub(r"[A-Za-z]+", repl, text)


def translate_entity_name(name: str | None, language: str | None = None) -> str | None:
    """Translate only the user-visible discovery name.

    Technical MQTT topics, register names, unique IDs and entity IDs are not
    touched by this function.
    """
    if not name:
        return name

    lang = normalize_language(language or runtime_language())
    if lang == "en":
        return name

    exact = _EXACT.get(lang, {}).get(name)
    if exact is not None:
        return exact

    # Generated naming patterns are common and should remain structurally clear.
    match = re.fullmatch(r"Bat(\d+) Serial", name)
    if match:
        n = match.group(1)
        return {
            "de": f"Bat{n} Seriennummer",
            "fr": f"Numéro de série Bat{n}",
            "es": f"Número de serie Bat{n}",
            "nl": f"Bat{n} serienummer",
        }[lang]

    match = re.fullmatch(r"Slot (\d+) (Enabled|Start Time|End Time|Mode|Power)", name)
    if match:
        n, field = match.groups()
        fields = {
            "de": {"Enabled": "Aktiviert", "Start Time": "Startzeit", "End Time": "Endzeit", "Mode": "Modus", "Power": "Leistung"},
            "fr": {"Enabled": "Activé", "Start Time": "Heure de début", "End Time": "Heure de fin", "Mode": "Mode", "Power": "Puissance"},
            "es": {"Enabled": "Activado", "Start Time": "Hora de inicio", "End Time": "Hora de fin", "Mode": "Modo", "Power": "Potencia"},
            "nl": {"Enabled": "Ingeschakeld", "Start Time": "Starttijd", "End Time": "Eindtijd", "Mode": "Modus", "Power": "Vermogen"},
        }
        return f"Slot {n} {fields[lang][field]}"

    translated = _replace_phrases(name, lang)
    translated = _replace_words(translated, lang)
    return translated
